import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import './globals.css'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import LanguageSelector from '@/src/components/languageSelector/languageSelector'
import { PokemonProvider } from '@/src/context/pokemonContext';
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode
  params: { locale: string }
}
export default async function LocaleLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {

  const messages = await getMessages()

  return (
    <html className={roboto.className} lang={locale}>
      <body>
    <PokemonProvider>

        <NextIntlClientProvider messages={messages}>
        <LanguageSelector/>
          {children}
        </NextIntlClientProvider>
    </PokemonProvider>
      </body>
    </html>
  )
}
